import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";
  return (
    <html lang="en">
      <body
        style={{ backgroundImage: `url(${basePath}/town.gif)` }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased wave-bg`}
      >
        {children}
      </body>
    </html>
  );
}
