import "./globals.css";
import { Press_Start_2P } from "next/font/google";

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-press-start",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";
  return (
    <html lang="en" className={pressStart2P.variable}>
      <body
        style={{ backgroundImage: `url(${basePath}/town.gif)` }}
        className="antialiased wave-bg"
      >
        {children}
      </body>
    </html>
  );
}
